Issue 129 - Fix StartWithSrpAuthAsync called by Sync context
aws/aws-sdk-net-extensions-cognito pull request #130
Opened 2023-08-21 19:54 UTC by swensorm

*Issue #, if available:*
https://github.com/aws/aws-sdk-net-extensions-cognito/issues/129

*Description of changes:*
Fixed bug with StartWithSrpAuthAsync(InitiateSrpAuthRequest) that would result in a deadlock scenario if the method was called by a synchronous context (e.g. .Result called on the method).

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-08-21 23:15 UTC, normj requested changes
If you search for "await " in the project you can see a few places where the `.ConfigureAwait(false)` is missing. Would you mind adding the `.ConfigureAwait(false)` change to those methods as well. 

Also can you change the version number in the project file to `2.5.1`.

2023-08-23 16:28 UTC, swensorm commented
Hi @philasmar.  As discussed in https://github.com/aws/aws-sdk-net-extensions-cognito/issues/129 there are 2 approaches to resolving the deadlocks.  One is to add `.ConfigureAwait(continueOnCapturedContext: false)` to all awaits currently missing it.  The other is to remove the unnecessary async/await wrapping and state machine generation from the methods which do not require it.

I am leaving it up to the AWS team to decide which approach they would prefer to go with and close the other.

2023-08-23 16:33 UTC, philasmar commented
> Hi @philasmar. As discussed in #129 there are 2 approaches to resolving the deadlocks. One is to add `.ConfigureAwait(continueOnCapturedContext: false)` to all awaits currently missing it. The other is to remove the unnecessary async/await wrapping and state machine generation from the methods which do not require it.
> 
> I am leaving it up to the AWS team to decide which approach they would prefer to go with and close the other.

Thanks for clarifying. I have closed the other PR in favor of this one. I continue reviewing this one.

2023-08-28 19:59 UTC, peterrsongg approved these changes
I double checked it was added everywhere with an async call, except for the readme, which I agree it doesn't need to be added there. Approving

2023-08-28 23:57 UTC, normj approved these changes
Thanks for going back and adding all of the `ConfigureAwait(false)` calls.

2023-08-29 00:11 UTC, swensorm commented
Thank you all for reviewing!  Happy to be a part of the project!

2023-08-31 00:42 UTC, merged

2023-08-31 02:57 UTC, normj commented
The PR has been released as part of version 2.5.1. Thanks again for the PR.

2023-08-31 03:36 UTC, swensorm commented
Wonderful news, thank you very much!  I will pull this into our project tomorrow.