feat: add support for .NET SDK V4
aws/aws-sdk-net-extensions-cognito pull request #156
Opened 2024-10-16 02:18 UTC by philasmar

*Issue #, if available:*
DOTNET-7759

*Description of changes:*
* Added .NET 8 target framework and marked as trimmable
* Updated the .NET SDK dependencies to the latest version 4.0.0-preview.4
* Add SourceLink support

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2024-10-16 21:39 UTC, 96malhar approved these changes

2024-10-17 04:25 UTC, normj requested changes
I wanted to build the packages locally to make sure they still looked right with all of the project file changes but I'm getting the following errors when I run `dotnet msbuild build.proj`

```
> dotnet msbuild .\build.proj
  build failed with 5 error(s) and 4 warning(s) (3.2s)
    C:\codebase\aws-logging-dotnet\test\AWS.Logger.SeriLog.Tests\AWS.Logger.SeriLog.Tests.csproj : error NU1903: Warning As Error: Package 'System.Text.Json' 8.0.0 has a known high severity vulnerability, https://github.com/advisories/GHSA-8g4q-xg66-9fp4 [C:\codebase\aws-logging-dotnet\AWS.Logger.sln]
    C:\codebase\aws-logging-dotnet\test\AWS.Logger.AspNetCore.Tests\AWS.Logger.AspNetCore.Tests.csproj : error NU1903: Warning As Error: Package 'System.Text.Json' 8.0.0 has a known high severity vulnerability, https://github.com/advisories/GHSA-8g4q-xg66-9fp4 [C:\codebase\aws-logging-dotnet\AWS.Logger.sln]
    C:\codebase\aws-logging-dotnet\test\AWS.Logger.AspNetCore.Tests\AWS.Logger.AspNetCore.Tests.csproj : error NU1903: Warning As Error: Package 'System.Text.Json' 8.0.0 has a known high severity vulnerability, https://github.com/advisories/GHSA-hh2w-p6rv-4g7w [C:\codebase\aws-logging-dotnet\AWS.Logger.sln]
    C:\codebase\aws-logging-dotnet\test\AWS.Logger.SeriLog.Tests\AWS.Logger.SeriLog.Tests.csproj : error NU1903: Warning As Error: Package 'System.Text.Json' 8.0.0 has a known high severity vulnerability, https://github.com/advisories/GHSA-hh2w-p6rv-4g7w [C:\codebase\aws-logging-dotnet\AWS.Logger.sln]
    C:\codebase\aws-logging-dotnet\samples\Serilog\SerilogTestCodeFromConfigRestrictedToMinimumLevel\SerilogTestCodeFromConfigRestrictedToMinimumLevel.csproj : warning NU1903: Package 'System.Text.Json' 8.0.0 has a known high severity vulnerability, https://github.com/advisories/GHSA-8g4q-xg66-9fp4 [C:\codebase\aws-logging-dotnet\AWS.Logger.sln]
    C:\codebase\aws-logging-dotnet\samples\Serilog\SerilogTestCodeFromConfigRestrictedToMinimumLevel\SerilogTestCodeFromConfigRestrictedToMinimumLevel.csproj : warning NU1903: Package 'System.Text.Json' 8.0.0 has a known high severity vulnerability, https://github.com/advisories/GHSA-hh2w-p6rv-4g7w [C:\codebase\aws-logging-dotnet\AWS.Logger.sln]
    C:\codebase\aws-logging-dotnet\samples\Serilog\SerilogTestCodeFromConfig\SerilogTestCodeFromConfig.csproj : warning NU1903: Package 'System.Text.Json' 8.0.0 has a known high severity vulnerability, https://github.com/advisories/GHSA-8g4q-xg66-9fp4 [C:\codebase\aws-logging-dotnet\AWS.Logger.sln]
    C:\codebase\aws-logging-dotnet\samples\Serilog\SerilogTestCodeFromConfig\SerilogTestCodeFromConfig.csproj : warning NU1903: Package 'System.Text.Json' 8.0.0 has a known high severity vulnerability, https://github.com/advisories/GHSA-hh2w-p6rv-4g7w [C:\codebase\aws-logging-dotnet\AWS.Logger.sln]
    C:\codebase\aws-logging-dotnet\build.proj(10,7): error MSB3073: The command "dotnet restore AWS.Logger.sln" exited with code 1.
```

2024-10-17 04:53 UTC, normj requested changes
The `GetUserPoolClientConfiguration` method in `CognitoUserPool` is passing in collections into `CognitoUserPoolClientConfiguration` which doesn't accept nulls. We should probably pass in empty collections if the the  `DescribeUserPoolClientAsync` returns back null collection.

I'm pretty sure the `AuthParameters` at this point should not be null but I would still add a defensive check: https://github.com/aws/aws-sdk-net-extensions-cognito/blob/master/src/Amazon.Extensions.CognitoAuthentication/CognitoUserAuthentication.cs#L76C33-L76C47

The null checks for the `challengeParameters` don't look complete in this method. UpdateUsernameAndSecretHash

Make sure the `ChallengeResponses` property is not null at this point: https://github.com/aws/aws-sdk-net-extensions-cognito/blob/master/src/Amazon.Extensions.CognitoAuthentication/CognitoUserAuthentication.cs#L96

The `ChallengeParameters` parameter needs some null checking: https://github.com/aws/aws-sdk-net-extensions-cognito/blob/master/src/Amazon.Extensions.CognitoAuthentication/CognitoUserAuthentication.cs#L175

Add some null checks on these collections. I'm not exactly sure where these collections are coming from but it might be from service responses.
https://github.com/aws/aws-sdk-net-extensions-cognito/blob/master/src/Amazon.Extensions.CognitoAuthentication/CognitoUser.cs#L774
https://github.com/aws/aws-sdk-net-extensions-cognito/blob/master/src/Amazon.Extensions.CognitoAuthentication/CognitoUser.cs#L792
https://github.com/aws/aws-sdk-net-extensions-cognito/blob/master/src/Amazon.Extensions.CognitoAuthentication/Util/CognitoAuthHelper.cs#L129
https://github.com/aws/aws-sdk-net-extensions-cognito/blob/master/src/Amazon.Extensions.CognitoAuthentication/CognitoDevice.cs#L317

2024-10-17 15:04 UTC, philasmar commented
> The `GetUserPoolClientConfiguration` method in `CognitoUserPool` is passing in collections into `CognitoUserPoolClientConfiguration` which doesn't accept nulls. We should probably pass in empty collections if the the `DescribeUserPoolClientAsync` returns back null collection.
> 
> I'm pretty sure the `AuthParameters` at this point should not be null but I would still add a defensive check: https://github.com/aws/aws-sdk-net-extensions-cognito/blob/master/src/Amazon.Extensions.CognitoAuthentication/CognitoUserAuthentication.cs#L76C33-L76C47
> 
> The null checks for the `challengeParameters` don't look complete in this method. UpdateUsernameAndSecretHash
> 
> Make sure the `ChallengeResponses` property is not null at this point: https://github.com/aws/aws-sdk-net-extensions-cognito/blob/master/src/Amazon.Extensions.CognitoAuthentication/CognitoUserAuthentication.cs#L96
> 
> The `ChallengeParameters` parameter needs some null checking: https://github.com/aws/aws-sdk-net-extensions-cognito/blob/master/src/Amazon.Extensions.CognitoAuthentication/CognitoUserAuthentication.cs#L175
> 
> Add some null checks on these collections. I'm not exactly sure where these collections are coming from but it might be from service responses. https://github.com/aws/aws-sdk-net-extensions-cognito/blob/master/src/Amazon.Extensions.CognitoAuthentication/CognitoUser.cs#L774 https://github.com/aws/aws-sdk-net-extensions-cognito/blob/master/src/Amazon.Extensions.CognitoAuthentication/CognitoUser.cs#L792 https://github.com/aws/aws-sdk-net-extensions-cognito/blob/master/src/Amazon.Extensions.CognitoAuthentication/Util/CognitoAuthHelper.cs#L129 https://github.com/aws/aws-sdk-net-extensions-cognito/blob/master/src/Amazon.Extensions.CognitoAuthentication/CognitoDevice.cs#L317

I went through the code base and added more defensive checks for collections.

2024-10-17 20:28 UTC, normj approved these changes

2024-10-17 21:03 UTC, merged